spec:
  shared_configuration:
    ## For ROKS and CNCF, this is used to enable the creation of ingresses. The default value is "false".
    sc_ingress_enable: false

    ## Service type to support CNCF Ingress creation, possible values are ClusterIP, NodePort
    sc_service_type: ClusterIP

    ## For ROKS and CNCF Ingress, provide TLS secret name for Ingress controller.
    sc_ingress_tls_secret_name: "<Required>"

    ## This is the deployment hostname suffix, this is optional and the default hostname suffix will be used as {meta.namespace}.router-canonicalhostname
    sc_deployment_hostname_suffix: "{{ meta.namespace }}"

    ## Used for single Ingress creation for both ECM and BAN.
    ## In case any custom annotation is needed for the environment provide below.
    ##  sc_ingress_annotations:
    ##   - kubernetes.io/ingress.class: nginx
    sc_ingress_annotations: